app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
  path:       /login
  defaults:   { _controller: AppBundle:Security:login }
logout:
  path:       /logout
posts_index:
    path:     /posts
    defaults: { _controller: AppBundle:Posts:index }
posts_create:
    path:     /posts/create
    defaults: { _controller: AppBundle:Posts:create }
posts_edit:
    path:     /posts/edit/{id}
    defaults: { _controller: AppBundle:Posts:edit }
users_index:
    path:     /users
    defaults: { _controller: AppBundle:Users:index }
users_create:
    path:     /users/create
    defaults: { _controller: AppBundle:Users:create }
users_edit:
    path:     /users/edit/{id}
    defaults: { _controller: AppBundle:Users:edit }

